Repository Git-For-Geeks-2-0/JavaScript-Mini-Projects, pull requests merged in 2023-10, with the labels that each got.

#16 feat: gui calculator
  GUI  calculator/.gitignore
  GUI  calculator/.yarn/releases/yarn-3.6.4.cjs
  GUI  calculator/.yarnrc.yml
  GUI  calculator/index.html
  GUI  calculator/package.json
  GUI  calculator/postcss.config.js
  GUI  calculator/prettier.config.cjs
  GUI  calculator/src/App.css
  GUI  calculator/src/App.tsx
  GUI  calculator/src/assets/calculator.png
  GUI  calculator/src/components/Calculator.tsx
  GUI  calculator/src/components/Display.tsx
  GUI  calculator/src/components/Equation.tsx
  GUI  calculator/src/components/Key.tsx
  GUI  calculator/src/components/Keypad.tsx
  GUI  calculator/src/components/Result.tsx
  GUI  calculator/src/index.css
  GUI  calculator/src/main.tsx
  GUI  calculator/src/vite-env.d.ts
  GUI  calculator/tailwind.config.js
  GUI  calculator/tsconfig.json
  GUI  calculator/tsconfig.node.json
  GUI  calculator/vite.config.ts
  GUI  calculator/yarn.lock
Labels: hacktoberfest, git-for-geeks-2.0, hacktoberfest-accpeted, medium

#15 feat: rgb
  rgb-color-background/index.html
  rgb-color-background/script.js
  rgb-color-background/style.css
Labels: hacktoberfest, git-for-geeks-2.0, hacktoberfest-accpeted, easy

#14 feat: countdown
  Count Down Timer/countdown.js
  Count Down Timer/index.html
  Count Down Timer/style.css
Labels: hacktoberfest, git-for-geeks-2.0, hacktoberfest-accpeted, easy

#17 Tic-Tac-Toe -Adesh Bode
  Tic-tac-toe/.vscode/settings.json
  Tic-tac-toe/ReadMe.md
  Tic-tac-toe/assets/game.svg
  Tic-tac-toe/index.html
  Tic-tac-toe/script.js
  Tic-tac-toe/style.css
Labels: hacktoberfest, git-for-geeks-2.0, GFG RCOEM, hacktoberfest-accpeted, easy
